//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gods
    {
        public int Id { get; set; }
        public int sub_type_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string image { get; set; }
        public int amount { get; set; }
        public decimal price { get; set; }
    }
}
